         JOB        I19  SETUP  : "END OF FILE" ON UNIT  5 AFTER RECORD #  18
         JOB        I25   TEST  : SUMMARY: NO DATA EXTRACTION FOR UPPERAIR
         JOB        I25   TEST  : SUMMARY: NO DATA QA FOR UPPERAIR
         JOB        I27   TEST  : SUMMARY: NO DATA QA FOR ONSITE
         SURFACE    I40  SFEXT  : *** SURFACE OBSERVATION EXTRACTION ***
20190101 SURFACE    W46 RDISHD  : SURFACE elev on LOCATION keyword ( 1437.00) differs from elev in ISHD file ( 1408.00).
         SURFACE    I41 FNDCOMDT: ASOS commission date FOUND for WBAN =  24015; CALL4 = KAKO; CALL3 = AKO; CommDate = 19960206
20190802 SURFACE    I49 RDISHD  : End of extract window after record:         7286
         SURFACE    I49 RDISHD  : The # of extracted records is:              3691
         SURFACE    W48 RDISHD  : The # of discarded records is:               606.  See 'Discarded_ISHD_Records.dat' file.
         SURFACE    W48 RDISHD  : The # of records flagged as calm is:         104
         SURFACE    W48 RDISHD  : The # of records flagged as variable is:      82
         SURFACE    I49 SFQATM  : End of file after data record:              3691
         SURFACE    I49  SFEXT  :  3691 SURFACE records extracted
         SURFACE    I48  SFEXT  : # ASOS wind data records based on commission date:   4524
  190303 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 23
  190305 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190305 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190307 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190307 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190307 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 10
  190307 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190307 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190307 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 11
  190307 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190307 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190307 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 12
  190307 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190307 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190307 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190307 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190309 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 24
  190311 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 11
  190312 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190312 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190312 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 15
  190312 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190315 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190315 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 17
  190315 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 20
  190316 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  190316 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  190316 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190316 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 15
  190316 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190319 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 21
  190319 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190320 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 24
  190320 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 24
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 01
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 01
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 01
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 02
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 02
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 02
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 03
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 03
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 03
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 04
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 04
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 04
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 05
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 05
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 05
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 06
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 06
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 06
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 07
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 07
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 07
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 08
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 08
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 08
  190321 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 09
  190321 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190321 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190324 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190328 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 05
  190331 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 11
  190331 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190331 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190331 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190402 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  190402 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  190402 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 07
  190402 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 08
  190402 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190404 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190404 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190404 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190405 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 07
  190405 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 11
  190405 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190405 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190405 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190406 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190406 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190407 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 15
  190407 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 03
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 03
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 04
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 04
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 04
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 05
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 05
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 05
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 06
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 06
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 06
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 07
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 07
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 07
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 08
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 08
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 08
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 09
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 10
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 11
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 12
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 13
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 14
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 15
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 15
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 16
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 17
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 18
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 18
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 19
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 19
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 19
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 20
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 20
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 20
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 21
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 21
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 21
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 22
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 22
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 22
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 23
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 23
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 23
  190411 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 24
  190411 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 24
  190411 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 24
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 01
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 01
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 01
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 02
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 02
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 02
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 03
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 03
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 03
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 04
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 04
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 04
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 05
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 05
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 05
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 06
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 06
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 06
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 07
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 07
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 07
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 08
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 08
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 08
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 09
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 10
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190412 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 12
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190412 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190412 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 13
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 14
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 15
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 15
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 16
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 17
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 18
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 18
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 19
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 19
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 19
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 20
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 20
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 20
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 21
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 21
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 21
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 22
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 22
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 22
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 23
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 23
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 23
  190413 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 24
  190413 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 24
  190413 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 24
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 01
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 01
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 01
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 02
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 02
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 02
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 03
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 03
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 03
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 04
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 04
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 04
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 05
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 05
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 05
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 06
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 06
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 06
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 07
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 07
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 07
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 08
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 08
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 08
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 09
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 13
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190414 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 18
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 18
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 19
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 19
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 19
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 20
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 20
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 20
  190414 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 21
  190414 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 21
  190414 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 21
  190415 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190415 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190415 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 10
  190415 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190415 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190415 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 11
  190415 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190415 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190415 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 12
  190415 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190415 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190415 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190416 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  190416 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 07
  190416 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190419 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190419 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190419 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190419 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190420 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190420 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190420 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190420 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190420 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190420 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190423 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 05
  190424 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 11
  190424 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190424 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190424 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190424 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 17
  190424 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190426 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190426 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190426 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190426 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190427 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190427 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190427 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190427 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 15
  190427 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190428 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190429 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190429 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190429 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190429 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190503 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190503 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190503 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190503 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190503 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190503 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 19
  190504 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190504 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190505 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190509 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 20
  190509 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 21
  190509 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190509 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 24
  190511 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 21
  190513 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190513 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190513 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190513 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190513 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190514 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190514 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190515 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190515 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 15
  190515 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190517 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 08
  190517 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190517 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190517 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190517 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190517 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190519 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190519 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190523 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 01
  190527 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190527 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190527 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190527 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190530 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190530 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 17
  190530 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 20
  190531 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 13
  190531 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190531 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190601 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 10
  190601 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190603 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 23
  190604 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 17
  190605 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190605 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190605 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190605 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190605 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 16
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 17
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 18
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 18
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 19
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 19
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 19
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 20
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 20
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 20
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 21
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 21
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 21
  190606 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 22
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 22
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 22
  190606 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 23
  190606 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 23
  190607 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 08
  190607 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 08
  190607 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 09
  190607 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190607 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 09
  190607 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 10
  190607 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190607 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190607 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 11
  190607 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190607 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190613 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190613 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190613 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 17
  190613 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 24
  190614 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 02
  190615 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190616 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190616 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 10
  190617 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190618 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  190618 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 19
  190618 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 20
  190618 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190618 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 23
  190619 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190619 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190619 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190619 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190620 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 10
  190622 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190622 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190622 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190623 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 01
  190625 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  190625 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190625 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190626 SURFACE    Q49 SFQASM  : TMPD MISSING FOR HR 11
  190626 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190626 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190626 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190627 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190627 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190628 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190629 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 09
  190630 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  190630 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190630 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190630 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 18
  190630 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 24
  190701 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190701 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190702 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 11
  190706 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190708 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190708 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 12
  190708 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  190709 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 13
  190709 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190709 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190709 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190710 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 12
  190710 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190710 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 16
  190710 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190711 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190712 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190712 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 13
  190712 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190712 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 15
  190712 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 23
  190715 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 10
  190715 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190715 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
  190715 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 13
  190715 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190715 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190715 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190718 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190718 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190718 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190718 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 17
  190721 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190721 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190721 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190724 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 10
  190724 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190724 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190724 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 12
  190724 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190724 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 16
  190725 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190725 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190725 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 18
  190726 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 09
  190726 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 10
  190726 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190726 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 11
  190727 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  190727 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 05
  190727 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  190727 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 08
  190727 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 11
  190727 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 24
  190730 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 14
  190730 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190730 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 16
  190730 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 17
  190731 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 14
  190731 SURFACE    Q49 SFQASM  : WSPD MISSING FOR HR 14
  190731 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 15
  190801 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 08
  190801 SURFACE    Q49 SFQASM  : WDIR MISSING FOR HR 13
         SURFACE    I49 SFQASM  : END OF FILE AFTER HOURLY OBS #  3691
