         JOB        I19  SETUP  : "END OF FILE" ON UNIT  5 AFTER RECORD #  16
         JOB        I26   TEST  : SUMMARY: NO DATA EXTRACTION FOR SURFACE
         JOB        I26   TEST  : SUMMARY: NO DATA QA FOR SURFACE
         JOB        I27   TEST  : SUMMARY: NO DATA QA FOR ONSITE
         UPPERAIR   I30  UAEXT  : **** UPPER AIR EXTRACTION ****
20190409 UPPERAIR   W36 GETFSL  : SDG SKIPPED: 1st LEVEL NOT TYPE 9, SDG #  922
20190530 UPPERAIR   W36 GETFSL  : SDG SKIPPED: 1st LEVEL NOT TYPE 9, SDG # 1023
         UPPERAIR   I39 GETFSL  : END-OF DATA WINDOW ENCOUNTERED
         UPPERAIR   I39  UAEXT  : 301 SOUNDINGS EXTRACTED
  190312 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190319 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190510 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190513 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190520 UPPERAIR   Q36 UAQASM  : COULD NOT RECOMPUTE HTS. FOR HR  06
  190521 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190525 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190531 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  18 AT LEVEL  3
  190601 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190602 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  18 AT LEVEL  1
  190609 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190610 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   2, HR: 18
  190610 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   3, HR: 18
  190610 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   4, HR: 18
  190610 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   5, HR: 18
  190610 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   6, HR: 18
  190626 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190630 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   4, HR: 18
  190630 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   5, HR: 18
  190630 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   6, HR: 18
  190710 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   2, HR: 06
  190710 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   3, HR: 06
  190710 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   4, HR: 06
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   2, HR: 18
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   3, HR: 18
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   4, HR: 18
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   5, HR: 18
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   6, HR: 18
  190714 UPPERAIR   Q35 HTCALC  : |CALC-OBS| SDG HTS > 50m: LVL   7, HR: 18
  190721 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
  190722 UPPERAIR   CLM UAQASM  : CALM WINDS FOR HR  06 AT LEVEL  1
         UPPERAIR   I39 UAQASM  : EOF AFTER UPPERAIR SOUNDING #   299
